version: "3.9"

services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warehouse
    volumes:
      - warehouse-db-volume:/var/lib/postgresql/data
    networks:
      - data_pipeline_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
    restart: always

volumes:
  warehouse-db-volume:

networks:
  data_pipeline_net:
    external: true
